import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Navbar} from "../components/Navbar"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-white flex flex-col  items-center`}
      >
        <Navbar/>
        <div className="  bg-white w-[93%] md:w-[50%]  mt-20 h-screen rounded-md">
          {children}

        </div>
      </body>
    </html>
  );
}
