import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Navbar} from "../../components/Navbar"
import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-white flex flex-col  items-center`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
        <Navbar/>
        <div className="  bg-white   mt-20 h-screen rounded-md">
          {children}

        </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
